on:
  push:
    tags:
      - '*'
name: CocoaPods Release
jobs:
  Release_Pod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push SerialExperiments.podspec